[tools]
rust = "1.91.1"
watchexec = "latest"

[tasks.day]
run = "cargo run --release -- $1"

[tasks.test]
run = 'bash -c "cargo test --lib day\$(printf %02d \$1)" -- $1'

[tasks.watch]
run = 'bash -c "watchexec -w src/ --exts rs --clear -- cargo test --lib day\$(printf %02d \$1)" -- $1'
